(function(g){var window=this;'use strict';var Pdu=function(Q,z){Q.F$("onAutonavCoundownStarted",z)},alR=function(Q){var z,H,f;
return Q==null?void 0:(z=Q.playerOverlays)==null?void 0:(H=z.playerOverlayRenderer)==null?void 0:(f=H.autoplay)==null?void 0:f.playerOverlayAutoplayRenderer},uX=function(Q,z,H){g.qP(Q.element,"ytp-suggestion-set",!!z.videoId);
var f=z.playlistId;H=z.MP(H?H:"mqdefault.jpg");var b=null,L=null;z instanceof g.jw&&(z.lengthText?(b=z.lengthText||null,L=z.VW||null):z.lengthSeconds&&(b=g.xU(z.lengthSeconds),L=g.xU(z.lengthSeconds,!0)));var u=!!f;f=u&&g.GZ(f).type==="RD";var X=z instanceof g.jw?z.isLivePlayback:null,v=z instanceof g.jw?z.isUpcoming:null,y=z.author,q=z.shortViewCount,M=z.publishedTimeText,C=[],t=[];y&&C.push(y);q&&(C.push(q),t.push(q));M&&t.push(M);H={title:z.title,author:y,author_and_views:C.join(" \u2022 "),aria_label:z.ariaLabel||
g.EB("Watch $TITLE",{TITLE:z.title}),duration:b,timestamp:L,url:z.ma(),is_live:X,is_upcoming:v,is_list:u,is_mix:f,background:H?"background-image: url("+H+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:z.SZ};z instanceof g.$a&&(H.playlist_length=z.playlistLength);Q.update(H)},SC=function(Q){var z=Q.C(),H=z.D;
g.m.call(this,{G:"a",J:"ytp-autonav-suggestion-card",T:{href:"{{url}}",target:H?z.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",lT:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],T:{style:"{{background}}"},W:[{G:"div",T:{"aria-label":"{{timestamp}}"},lT:["ytp-autonav-timestamp"],BI:"{{duration}}"},{G:"div",lT:["ytp-autonav-live-stamp"],BI:"Live"},{G:"div",
lT:["ytp-autonav-upcoming-stamp"],BI:"Upcoming"},{G:"div",J:"ytp-autonav-list-overlay",W:[{G:"div",J:"ytp-autonav-mix-text",BI:"Mix"},{G:"div",J:"ytp-autonav-mix-icon"}]}]},{G:"div",lT:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],BI:"{{title}}"},{G:"div",lT:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],BI:"{{author}}"},{G:"div",lT:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],BI:"{{views_and_publish_time}}"}]});this.K=Q;this.suggestion=
null;this.Z=H;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},XW=function(Q,z){z=z===void 0?!1:z;
g.m.call(this,{G:"div",J:"ytp-autonav-endscreen-countdown-overlay"});var H=this;this.Y=z;this.cancelCommand=this.j=void 0;this.L=0;this.container=new g.m({G:"div",J:"ytp-autonav-endscreen-countdown-container"});g.W(this,this.container);this.container.Gv(this.element);z=Q.C();var f=z.D;this.K=Q;this.suggestion=null;this.onVideoDataChange("newdata",this.K.getVideoData());this.X(Q,"videodatachange",this.onVideoDataChange);this.Z=new g.m({G:"div",J:"ytp-autonav-endscreen-upnext-container",T:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",J:"ytp-autonav-endscreen-upnext-header"},{G:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",BI:"{{autoplayAlternativeHeader}}"},{G:"a",J:"ytp-autonav-endscreen-link-container",T:{href:"{{url}}",target:f?z.U:""},W:[{G:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",T:{style:"{{background}}"},W:[{G:"div",T:{"aria-label":"{{timestamp}}"},lT:["ytp-autonav-timestamp"],
BI:"{{duration}}"},{G:"div",lT:["ytp-autonav-live-stamp"],BI:"Live"},{G:"div",lT:["ytp-autonav-upcoming-stamp"],BI:"Upcoming"}]},{G:"div",J:"ytp-autonav-endscreen-video-info",W:[{G:"div",J:"ytp-autonav-endscreen-premium-badge"},{G:"div",J:"ytp-autonav-endscreen-upnext-title",BI:"{{title}}"},{G:"div",J:"ytp-autonav-endscreen-upnext-author",BI:"{{author}}"},{G:"div",J:"ytp-autonav-view-and-date",BI:"{{views_and_publish_time}}"},{G:"div",J:"ytp-autonav-author-and-view",BI:"{{author_and_views}}"}]}]}]});
g.W(this,this.Z);this.Z.Gv(this.container.element);f||this.X(this.Z.Mc("ytp-autonav-endscreen-link-container"),"click",this.U1);this.K.createClientVe(this.container.element,this,115127);this.K.createClientVe(this.Z.Mc("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.m({G:"div",J:"ytp-autonav-overlay"});g.W(this,this.overlay);this.overlay.Gv(this.container.element);this.B=new g.m({G:"div",J:"ytp-autonav-endscreen-button-container"});g.W(this,this.B);this.B.Gv(this.container.element);
this.cancelButton=new g.m({G:"button",lT:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",z.V("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],T:{"aria-label":"Cancel autoplay"},BI:"Cancel"});g.W(this,this.cancelButton);this.cancelButton.Gv(this.B.element);this.cancelButton.listen("click",this.Pv,this);this.K.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.m({G:"a",lT:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
z.V("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],T:{href:"{{url}}",role:"button","aria-label":"Play next video"},BI:"Play Now"});g.W(this,this.playButton);this.playButton.Gv(this.B.element);this.playButton.listen("click",this.U1,this);this.K.createServerVe(this.playButton.element,this.playButton,!0);(z=this.K.getVideoData())&&UHm(this,z);this.D=new g.e_(function(){cjR(H)},500);
g.W(this,this.D);this.TA();this.X(Q,"autonavvisibility",this.TA);this.K.V("web_autonav_color_transition")&&(this.X(Q,"autonavchange",this.wj),this.X(Q,"onAutonavCoundownStarted",this.b53))},vF=function(Q){var z=Q.K.A8(!0,Q.K.isFullscreen());
g.qP(Q.container.element,"ytp-autonav-endscreen-small-mode",Q.HB(z));g.qP(Q.container.element,"ytp-autonav-endscreen-is-premium",!!Q.suggestion&&!!Q.suggestion.kZl);g.qP(Q.K.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!Q.K.T1());g.qP(Q.K.getRootNode(),"countdown-running",Q.JB());g.qP(Q.container.element,"ytp-player-content",Q.K.T1());g.q2(Q.overlay.element,{width:z.width+"px"});if(!Q.JB()){Q.K.T1()?igs(Q,Math.round(hUs(Q)/1E3)):igs(Q);z=!!Q.suggestion&&!!Q.suggestion.SZ;var H=Q.K.T1()||
!z;g.qP(Q.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!H&&z);g.qP(Q.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",H&&!z);Q.B.Ho(Q.K.T1());g.qP(Q.element,"ytp-enable-w2w-color-transitions",W_u(Q))}},cjR=function(Q){var z=hUs(Q),H=Math,f=H.min;
var b=Q.L?Date.now()-Q.L:0;H=f.call(H,b,z);igs(Q,Math.ceil((z-H)/1E3));z-H<=500&&Q.JB()?Q.select(!0):Q.JB()&&Q.D.start()},hUs=function(Q){if(Q.K.isFullscreen()){var z;
Q=(z=Q.K.getVideoData())==null?void 0:z.W_;return Q===-1||Q===void 0?8E3:Q}return Q.K.It()>=0?Q.K.It():g.qf(Q.K.C().experiments,"autoplay_time")||1E4},UHm=function(Q,z){z=z.getWatchNextResponse();
var H,f;z=(H=alR(z))==null?void 0:(f=H.nextButton)==null?void 0:f.buttonRenderer;Q.j=z==null?void 0:z.navigationEndpoint;H=z==null?void 0:z.trackingParams;Q.playButton&&H&&Q.K.setTrackingParams(Q.playButton.element,H)},W_u=function(Q){var z;
return!((z=Q.K.getVideoData())==null||!z.watchToWatchTransitionRenderer)},igs=function(Q,z){z=z===void 0?-1:z;
Q=Q.Z.Mc("ytp-autonav-endscreen-upnext-header");g.Lm(Q);if(z>=0){z=String(z);var H="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Up next in $SECONDS".indexOf(H);if(f>=0){Q.appendChild(g.fm("Up next in $SECONDS".slice(0,f)));var b=g.Hx("span");g.LZ(b,"ytp-autonav-endscreen-upnext-header-countdown-number");g.vx(b,z);Q.appendChild(b);Q.appendChild(g.fm("Up next in $SECONDS".slice(f+H.length)));return}}g.vx(Q,"Up next")},yl=function(Q,z){g.m.call(this,{G:"div",
lT:["html5-endscreen","ytp-player-content",z||"base-endscreen"]});this.created=!1;this.player=Q},qw=function(Q){g.m.call(this,{G:"div",
lT:["ytp-upnext","ytp-player-content"],T:{"aria-label":"{{aria_label}}"},W:[{G:"div",J:"ytp-cued-thumbnail-overlay-image",T:{style:"{{background}}"}},{G:"span",J:"ytp-upnext-top",W:[{G:"span",J:"ytp-upnext-header",BI:"Up Next"},{G:"span",J:"ytp-upnext-title",BI:"{{title}}"},{G:"span",J:"ytp-upnext-author",BI:"{{author}}"}]},{G:"a",J:"ytp-upnext-autoplay-icon",T:{role:"button",href:"{{url}}","aria-label":"Play next video"},W:[{G:"svg",T:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
W:[{G:"circle",J:"ytp-svg-autoplay-circle",T:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",J:"ytp-svg-autoplay-ring",T:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",J:"ytp-svg-fill",T:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",J:"ytp-upnext-bottom",W:[{G:"span",J:"ytp-upnext-cancel"},{G:"span",J:"ytp-upnext-paused",
BI:"Autoplay is paused"}]}]});this.api=Q;this.cancelButton=null;this.j=this.Mc("ytp-svg-autoplay-ring");this.L=this.notification=this.Z=this.suggestion=null;this.D=new g.e_(this.kO,5E3,this);this.B=0;var z=this.Mc("ytp-upnext-cancel");this.cancelButton=new g.m({G:"button",lT:["ytp-upnext-cancel-button","ytp-button"],T:{tabindex:"0","aria-label":"Cancel autoplay"},BI:"Cancel"});g.W(this,this.cancelButton);this.cancelButton.listen("click",this.xH,this);this.cancelButton.Gv(z);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.W(this,this.D);this.api.createClientVe(this.element,this,18788);z=this.Mc("ytp-upnext-autoplay-icon");this.X(z,"click",this.ze);this.api.createClientVe(z,this,115130);this.g8();this.X(Q,"autonavvisibility",this.g8);this.X(Q,"mdxnowautoplaying",this.Opc);this.X(Q,"mdxautoplaycanceled",this.Zp3);g.qP(this.element,"ytp-upnext-mobile",this.api.C().B)},DHs=function(Q,z){if(z)return z;
if(Q.api.isFullscreen()){var H;Q=(H=Q.api.getVideoData())==null?void 0:H.W_;return Q===-1||Q===void 0?8E3:Q}return Q.api.It()>=0?Q.api.It():g.qf(Q.api.C().experiments,"autoplay_time")||1E4},K_O=function(Q,z){z=DHs(Q,z);
var H=Math,f=H.min;var b=(0,g.NV)()-Q.B;H=f.call(H,b,z);z=z===0?1:Math.min(H/z,1);Q.j.setAttribute("stroke-dashoffset",""+-211*(z+1));z>=1&&Q.JB()&&Q.api.getPresentingPlayerType()!==3?Q.select(!0):Q.JB()&&Q.Z.start()},Mw=function(Q){yl.call(this,Q,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.m({G:"div",J:"ytp-suggestion-panel",W:[{G:"div",lT:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],BI:"More videos"}]});this.N=new g.m({G:"div",J:"ytp-suggestions-container"});this.videos=[];this.L=null;this.j=this.Y=!1;this.B=new XW(this.player);g.W(this,this.B);this.B.Gv(this.element);Q.getVideoData().Ci?this.Z=this.B:(this.Z=new qw(Q),g.sZ(this.player,this.Z.element,4),g.W(this,this.Z));this.overlay=new g.m({G:"div",
J:"ytp-autonav-overlay-cancelled-state"});g.W(this,this.overlay);this.overlay.Gv(this.element);this.D=new g.Bt(this);g.W(this,this.D);g.W(this,this.table);this.table.Gv(this.element);this.table.show();g.W(this,this.N);this.N.Gv(this.table.element);this.hide()},Cz=function(Q){var z=Q.T1();
z!==Q.j&&(Q.j=z,Q.player.publish("autonavvisibility"),Q.j?(Q.B!==Q.Z&&Q.B.hide(),Q.table.hide()):(Q.B!==Q.Z&&Q.B.show(),Q.table.show()))},tV=function(Q,z){g.m.call(this,{G:"button",
lT:["ytp-watch-on-youtube-button","ytp-button"],BI:"{{content}}"});this.K=Q;this.buttonType=this.buttonType=z;this.Jx();this.buttonType===2&&g.SK(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Jx);this.Ho(!0)},Eq=function(Q,z){yl.call(this,Q,"embeds-lite-endscreen");
this.K=Q;this.Z=z;this.K.createClientVe(this.element,this,156943);this.watchButton=new tV(Q,2);g.W(this,this.watchButton);this.watchButton.Gv(this.element);this.hide()},VLm=function(Q){yl.call(this,Q,"subscribecard-endscreen");
this.Z=new g.m({G:"div",J:"ytp-subscribe-card",W:[{G:"img",J:"ytp-author-image",T:{src:"{{profilePicture}}"}},{G:"div",J:"ytp-subscribe-card-right",W:[{G:"div",J:"ytp-author-name",BI:"{{author}}"},{G:"div",J:"html5-subscribe-button-container"}]}]});g.W(this,this.Z);this.Z.Gv(this.element);var z=Q.getVideoData();this.subscribeButton=new g.QI("Subscribe",null,"Unsubscribe",null,!0,!1,z.HG,z.subscribed,"trailer-endscreen",null,Q,!1);g.W(this,this.subscribeButton);this.subscribeButton.Gv(this.Z.Mc("html5-subscribe-button-container"));
this.X(Q,"videodatachange",this.Jh);this.Jh();this.hide()},pz=function(Q){var z=Q.C(),H=g.AI||g.jN?{style:"will-change: opacity"}:void 0,f=z.D,b=["ytp-videowall-still"];
z.B&&b.push("ytp-videowall-show-text");g.m.call(this,{G:"a",lT:b,T:{href:"{{url}}",target:f?z.U:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",J:"ytp-videowall-still-image",T:{style:"{{background}}"}},{G:"span",J:"ytp-videowall-still-info",T:{"aria-hidden":"true"},W:[{G:"span",J:"ytp-videowall-still-info-bg",W:[{G:"span",J:"ytp-videowall-still-info-content",T:H,W:[{G:"span",J:"ytp-videowall-still-info-title",BI:"{{title}}"},
{G:"span",J:"ytp-videowall-still-info-author",BI:"{{author_and_views}}"},{G:"span",J:"ytp-videowall-still-info-live",BI:"Live"},{G:"span",J:"ytp-videowall-still-info-duration",BI:"{{duration}}"}]}]}]},{G:"span",lT:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],T:{"aria-hidden":"true"},W:[{G:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",J:"ytp-videowall-still-listlabel-length",W:[" (",{G:"span",BI:"{{playlist_length}}"},")"]}]},{G:"span",lT:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],T:{"aria-hidden":"true"},W:[{G:"span",J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",J:"ytp-videowall-still-listlabel-length",BI:" (50+)"}]}]});this.suggestion=null;this.B=f;this.api=Q;this.Z=new g.Bt(this);g.W(this,this.Z);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.Z.X(Q,"videodatachange",this.onVideoDataChange);Q.createServerVe(this.element,this);this.onVideoDataChange()},nz=function(Q){yl.call(this,Q,"videowall-endscreen");
var z=this;this.K=Q;this.L=0;this.stills=[];this.D=this.videoData=null;this.j=this.N=!1;this.U=null;this.B=new g.Bt(this);g.W(this,this.B);this.Y=new g.e_(function(){g.SK(z.element,"ytp-show-tiles")},0);
g.W(this,this.Y);var H=new g.m({G:"button",lT:["ytp-button","ytp-endscreen-previous"],T:{"aria-label":"Previous"},W:[g.Zv()]});g.W(this,H);H.Gv(this.element);H.listen("click",this.kH,this);this.table=new g.yR({G:"div",J:"ytp-endscreen-content"});g.W(this,this.table);this.table.Gv(this.element);H=new g.m({G:"button",lT:["ytp-button","ytp-endscreen-next"],T:{"aria-label":"Next"},W:[g.G8()]});g.W(this,H);H.Gv(this.element);H.listen("click",this.Lm,this);Q.getVideoData().Ci?this.Z=new XW(Q,!0):this.Z=
new qw(Q);g.W(this,this.Z);g.sZ(this.player,this.Z.element,4);Q.createClientVe(this.element,this,158789);this.hide()},gF=function(Q){return g.BG(Q.player)&&Q.A1()&&!Q.D},Z9=function(Q){var z=Q.T1();
z!==Q.N&&(Q.N=z,Q.player.publish("autonavvisibility"))},Gk=function(Q){yl.call(this,Q,"watch-again-on-youtube-endscreen");
this.watchButton=new tV(Q,1);g.W(this,this.watchButton);this.watchButton.Gv(this.element);g.wd6(Q)&&(this.Z=new g.Tm(Q),g.W(this,this.Z),this.B=new g.m({G:"div",lT:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],T:{tabIndex:"-1"},W:[this.Z]}),g.W(this,this.B),this.Z.Gv(this.B.element),this.B.Gv(this.element));Q.createClientVe(this.element,this,156914);this.hide()},kMm=function(Q){g.g3.call(this,Q);
var z=this;this.endScreen=null;this.B=this.Z=this.L=this.D=!1;this.listeners=new g.Bt(this);g.W(this,this.listeners);var H=Q.C(),f=Q.getVideoData();f=f&&f.limitedPlaybackDurationInSeconds!==0;g.q0(g.s8(H))&&f&&!g.Ig(Q)?(this.B=!0,this.endScreen=new Eq(Q,g.EZ(Q))):Q.isEmbedsShortsMode()?this.endScreen=new Gk(Q):dHs(Q)?(this.D=!0,mHL(this),this.Z?this.endScreen=new Mw(Q):this.endScreen=new nz(Q)):H.Ci?this.endScreen=new VLm(Q):this.endScreen=new yl(Q);g.W(this,this.endScreen);g.sZ(Q,this.endScreen.element,
4);w4J(this);this.listeners.X(Q,"videodatachange",this.onVideoDataChange,this);this.listeners.X(Q,g.bc("endscreen"),function(b){z.onCueRangeEnter(b)});
this.listeners.X(Q,g.Li("endscreen"),function(b){z.onCueRangeExit(b)})},mHL=function(Q){var z=Q.player.getVideoData();
if(!z||Q.Z===z.xr&&Q.L===z.Ci)return!1;Q.Z=z.xr;Q.L=z.Ci;return!0},dHs=function(Q){Q=Q.C();
return Q.p5&&!Q.Ci&&!Q.disableOrganicUi},w4J=function(Q){Q.player.Ys("endscreen");
var z=Q.player.getVideoData();z=new g.HD(Math.max((z.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var H=new g.HD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});Q.player.UZ([z,H])};
g.OZ.prototype.It=g.fn(14,function(){return this.app.It()});
g.gQ.prototype.It=g.fn(13,function(){return this.getVideoData().uY});
g.$1.prototype.Nt=g.fn(12,function(Q){this.fE().Nt(Q)});
g.nU.prototype.Nt=g.fn(11,function(Q){this.Z!==Q&&(this.Z=Q,this.Jh())});
g.IY.prototype.Nt=g.fn(10,function(Q){this.overflowButton&&this.overflowButton.Nt(Q)});
g.$1.prototype.Fx=g.fn(9,function(Q){this.fE().Fx(Q)});
g.jO.prototype.Fx=g.fn(8,function(Q){this.B!==Q&&(this.B=Q,this.Jh())});
g.IY.prototype.Fx=g.fn(7,function(Q){this.shareButton&&this.shareButton.Fx(Q)});
g.$1.prototype.kK=g.fn(6,function(Q){this.fE().kK(Q)});
g.d3.prototype.kK=g.fn(5,function(Q){this.VZ!==Q&&(this.VZ=Q,this.GY())});
g.$1.prototype.Lx=g.fn(4,function(Q){this.fE().Lx(Q)});
g.IY.prototype.Lx=g.fn(3,function(Q){this.AA!==Q&&(this.AA=Q,this.bF())});g.p(SC,g.m);SC.prototype.select=function(){this.K.cN(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Pd||void 0)&&this.K.logClick(this.element)};
SC.prototype.onClick=function(Q){g.LK(Q,this.K,this.Z,this.suggestion.sessionData||void 0)&&this.select()};
SC.prototype.onKeyPress=function(Q){switch(Q.keyCode){case 13:case 32:Q.defaultPrevented||(this.select(),Q.preventDefault())}};g.p(XW,g.m);g.S=XW.prototype;g.S.yV=function(Q){this.suggestion!==Q&&(this.suggestion=Q,uX(this.Z,Q),this.playButton.updateValue("url",this.suggestion.ma()),vF(this))};
g.S.JB=function(){return this.L>0};
g.S.s0=function(){this.JB()||(this.L=Date.now(),cjR(this),Pdu(this.K,hUs(this)),g.qP(this.K.getRootNode(),"countdown-running",this.JB()))};
g.S.xd=function(){this.zY();cjR(this);var Q=this.Z.Mc("ytp-autonav-endscreen-upnext-header");Q&&g.vx(Q,"Up next")};
g.S.zY=function(){this.JB()&&(this.D.stop(),this.L=0)};
g.S.select=function(Q){this.K.nextVideo(!1,Q===void 0?!1:Q);this.zY()};
g.S.U1=function(Q){g.LK(Q,this.K)&&(Q.currentTarget===this.playButton.element?this.K.logClick(this.playButton.element):Q.currentTarget===this.Z.Mc("ytp-autonav-endscreen-link-container")&&(Q=this.Z.Mc("ytp-autonav-endscreen-link-container"),this.K.logVisibility(Q,!0),this.K.logClick(Q)),this.j?(this.K.F$("innertubeCommand",this.j),this.zY()):this.select())};
g.S.Pv=function(){this.K.logClick(this.cancelButton.element);g.Jf(this.K,!0);this.cancelCommand&&this.K.F$("innertubeCommand",this.cancelCommand)};
g.S.onVideoDataChange=function(Q,z){UHm(this,z);Q=z.getWatchNextResponse();var H,f;Q=(H=alR(Q))==null?void 0:(f=H.cancelButton)==null?void 0:f.buttonRenderer;this.cancelCommand=Q==null?void 0:Q.command};
g.S.b53=function(Q){if(W_u(this)){var z=this.K.getVideoData().watchToWatchTransitionRenderer,H=z==null?void 0:z.fromColorPaletteDark;z=z==null?void 0:z.toColorPaletteDark;if(H&&z){var f=this.element;f.style.setProperty("--w2w-start-background-color",g.iA(H.surgeColor));f.style.setProperty("--w2w-start-primary-text-color",g.iA(H.primaryTitleColor));f.style.setProperty("--w2w-start-secondary-text-color",g.iA(H.secondaryTitleColor));f.style.setProperty("--w2w-end-background-color",g.iA(z.surgeColor));
f.style.setProperty("--w2w-end-primary-text-color",g.iA(z.primaryTitleColor));f.style.setProperty("--w2w-end-secondary-text-color",g.iA(z.secondaryTitleColor));f.style.setProperty("--w2w-animation-duration",Q+"ms")}g.qP(this.element,"ytp-w2w-animate",!0)}};
g.S.wj=function(Q){this.K.V("web_autonav_color_transition")&&Q!==2&&g.qP(this.element,"ytp-w2w-animate",!1)};
g.S.TA=function(){var Q=this.K.T1();this.Y&&this.LH!==Q&&this.Ho(Q);vF(this);this.K.logVisibility(this.container.element,Q);this.K.logVisibility(this.cancelButton.element,Q);this.K.logVisibility(this.Z.Mc("ytp-autonav-endscreen-link-container"),Q);this.K.logVisibility(this.playButton.element,Q)};
g.S.HB=function(Q){return Q.width<400||Q.height<459};g.p(yl,g.m);g.S=yl.prototype;g.S.create=function(){this.created=!0};
g.S.destroy=function(){this.created=!1};
g.S.A1=function(){return!1};
g.S.T1=function(){return!1};
g.S.qq=function(){return!1};g.p(qw,g.m);g.S=qw.prototype;g.S.kO=function(){this.notification&&(this.D.stop(),this.DS(this.L),this.L=null,this.notification.close(),this.notification=null)};
g.S.yV=function(Q){this.suggestion=Q;uX(this,Q,"hqdefault.jpg")};
g.S.g8=function(){this.Ho(this.api.T1());this.api.logVisibility(this.element,this.api.T1());this.api.logVisibility(this.Mc("ytp-upnext-autoplay-icon"),this.api.T1());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.T1())};
g.S.amh=function(){window.focus();this.kO()};
g.S.s0=function(Q){var z=this;this.JB()||(g.XN("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.NV)(),this.Z=new g.e_(function(){K_O(z,Q)},25),K_O(this,Q),Pdu(this.api,DHs(this,Q)));
g.vO(this.element,"ytp-upnext-autoplay-paused")};
g.S.hide=function(){g.m.prototype.hide.call(this)};
g.S.JB=function(){return!!this.Z};
g.S.xd=function(){this.zY();this.B=(0,g.NV)();K_O(this);g.SK(this.element,"ytp-upnext-autoplay-paused")};
g.S.zY=function(){this.JB()&&(this.Z.dispose(),this.Z=null)};
g.S.select=function(Q){Q=Q===void 0?!1:Q;if(this.api.C().V("autonav_notifications")&&Q&&window.Notification&&typeof document.hasFocus==="function"){var z=Notification.permission;z==="default"?Notification.requestPermission():z!=="granted"||document.hasFocus()||(this.kO(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.MP()}),this.L=this.X(this.notification,"click",this.amh),this.D.start())}this.zY();this.api.nextVideo(!1,Q)};
g.S.ze=function(Q){!g.XU(this.cancelButton.element,Q.target)&&g.LK(Q,this.api)&&(this.api.T1()&&this.api.logClick(this.Mc("ytp-upnext-autoplay-icon")),this.select())};
g.S.xH=function(){this.api.T1()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Jf(this.api,!0)};
g.S.Opc=function(Q){this.api.getPresentingPlayerType();this.show();this.s0(Q)};
g.S.Zp3=function(){this.api.getPresentingPlayerType();this.zY();this.hide()};
g.S.zv=function(){this.zY();this.kO();g.m.prototype.zv.call(this)};g.p(Mw,yl);g.S=Mw.prototype;g.S.create=function(){yl.prototype.create.call(this);this.D.X(this.player,"appresize",this.kx);this.D.X(this.player,"onVideoAreaChange",this.kx);this.D.X(this.player,"videodatachange",this.onVideoDataChange);this.D.X(this.player,"autonavchange",this.r3);this.D.X(this.player,"onAutonavCancelled",this.Bv);this.onVideoDataChange()};
g.S.show=function(){yl.prototype.show.call(this);(this.Y||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.Jf(this.player,!1);g.BG(this.player)&&this.A1()&&!this.L?(Cz(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.Z.select(!0):this.Z.s0():this.videoData.autonavState===3&&this.Z.xd()):(g.Jf(this.player,!0),Cz(this));this.kx()};
g.S.hide=function(){yl.prototype.hide.call(this);this.Z.xd();Cz(this)};
g.S.kx=function(){var Q=this.player.A8(!0,this.player.isFullscreen());Cz(this);vF(this.B);g.qP(this.element,"ytp-autonav-cancelled-small-mode",this.HB(Q));g.qP(this.element,"ytp-autonav-cancelled-tiny-mode",this.g0(Q));g.qP(this.element,"ytp-autonav-cancelled-mini-mode",Q.width<=400||Q.height<=360);this.overlay&&g.q2(this.overlay.element,{width:Q.width+"px"});if(!this.j)for(Q=0;Q<this.videos.length;Q++)g.qP(this.videos[Q].element,"ytp-suggestion-card-with-margin",Q%2===1)};
g.S.onVideoDataChange=function(){var Q=this.player.getVideoData();if(this.videoData!==Q&&Q){this.videoData=Q;if((Q=this.videoData.suggestions)&&Q.length||this.player.V("web_player_autonav_empty_suggestions_fix")){var z=g.lF(this.videoData);z&&(this.Z.yV(z),this.Z!==this.B&&this.B.yV(z))}if(Q&&Q.length)for(z=0;z<TeY.length;++z){var H=TeY[z];if(Q&&Q[H]){this.videos[z]=new SC(this.player);var f=this.videos[z];H=Q[H];f.suggestion!==H&&(f.suggestion=H,uX(f,H));g.W(this,this.videos[z]);this.videos[z].Gv(this.N.element)}}this.kx()}};
g.S.r3=function(Q){Q===1?(this.Y=!1,this.L=this.videoData.clientPlaybackNonce,this.Z.zY(),this.LH&&this.kx()):(this.Y=!0,this.T1()&&(Q===2?this.Z.s0():Q===3&&this.Z.xd()))};
g.S.Bv=function(Q){Q?this.r3(1):(this.L=null,this.Y=!1)};
g.S.A1=function(){return this.videoData.autonavState!==1};
g.S.HB=function(Q){return(Q.width<910||Q.height<459)&&!this.g0(Q)&&!(Q.width<=400||Q.height<=360)};
g.S.g0=function(Q){return Q.width<800&&!(Q.width<=400||Q.height<=360)};
g.S.T1=function(){return this.LH&&g.BG(this.player)&&this.A1()&&!this.L};
var TeY=[1,3,2,4];g.p(tV,g.m);g.S=tV.prototype;g.S.Jx=function(){switch(this.buttonType){case 1:var Q="Watch again on YouTube";var z=156915;break;case 2:Q="Continue watching on YouTube";z=156942;break;default:Q="Continue watching on YouTube",z=156942}this.update({content:Q});this.K.hasVe(this.element)&&this.K.destroyVe(this.element);this.K.createClientVe(this.element,this,z)};
g.S.onClick=function(Q){this.K.V("web_player_log_click_before_generating_ve_conversion_params")&&this.K.logClick(this.element);g.uo(this.getVideoUrl(),this.K,Q);this.K.V("web_player_log_click_before_generating_ve_conversion_params")||this.K.logClick(this.element)};
g.S.getVideoUrl=function(){var Q=!0;switch(this.buttonType){case 1:Q=!0;break;case 2:Q=!1}Q=this.K.getVideoUrl(Q,!1,!1,!0);var z=this.K.C();if(g.xh(z)){var H={};g.xh(z)&&g.yw(this.K,"addEmbedsConversionTrackingParams",[H]);Q=g.Ve(Q,H)}return Q};
g.S.logVisibility=function(){this.K.logVisibility(this.element,this.LH&&this.S)};
g.S.show=function(){g.m.prototype.show.call(this);this.logVisibility()};
g.S.hide=function(){g.m.prototype.hide.call(this);this.logVisibility()};
g.S.pH=function(Q){g.m.prototype.pH.call(this,Q);this.logVisibility()};g.p(Eq,yl);Eq.prototype.show=function(){this.player.getPlayerState()!==3&&(yl.prototype.show.call(this),this.Z.Lx(!0),this.Z.Fx(!0),this.K.C().QN||this.Z.Nt(!0),this.K.logVisibility(this.element,!0),this.watchButton.pH(!0))};
Eq.prototype.hide=function(){yl.prototype.hide.call(this);this.Z.Lx(!1);this.Z.Fx(!1);this.Z.Nt(!1);this.K.logVisibility(this.element,!1);this.watchButton.pH(!1)};g.p(VLm,yl);VLm.prototype.Jh=function(){var Q=this.player.getVideoData();this.Z.update({profilePicture:Q.profilePicture,author:Q.author});this.subscribeButton.channelId=Q.HG;var z=this.subscribeButton;Q.subscribed?z.Z():z.B()};g.p(pz,g.m);pz.prototype.select=function(){this.api.cN(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Pd||void 0)&&this.api.logClick(this.element)};
pz.prototype.onClick=function(Q){if(g.xh(this.api.C())&&this.api.V("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var z=this.suggestion.ma(),H={};g.Af(this.api,H);z=g.Ve(z,H);g.uo(z,this.api,Q)}else g.LK(Q,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
pz.prototype.onKeyPress=function(Q){switch(Q.keyCode){case 13:case 32:Q.defaultPrevented||(this.select(),Q.preventDefault())}};
pz.prototype.onVideoDataChange=function(){var Q=this.api.getVideoData(),z=this.api.C();this.B=Q.gV?!1:z.D};g.p(nz,yl);g.S=nz.prototype;g.S.create=function(){yl.prototype.create.call(this);var Q=this.player.getVideoData();Q&&(this.videoData=Q);this.nZ();this.B.X(this.player,"appresize",this.nZ);this.B.X(this.player,"onVideoAreaChange",this.nZ);this.B.X(this.player,"videodatachange",this.onVideoDataChange);this.B.X(this.player,"autonavchange",this.JC);this.B.X(this.player,"onAutonavCancelled",this.qw);Q=this.videoData.autonavState;Q!==this.U&&this.JC(Q);this.B.X(this.element,"transitionend",this.c$3)};
g.S.destroy=function(){g.Aq(this.B);g.Xx(this.stills);this.stills=[];yl.prototype.destroy.call(this);g.vO(this.element,"ytp-show-tiles");this.Y.stop();this.U=this.videoData.autonavState};
g.S.A1=function(){return this.videoData.autonavState!==1};
g.S.show=function(){var Q=this.LH;yl.prototype.show.call(this);g.vO(this.element,"ytp-show-tiles");this.player.C().B?g.Re(this.Y):this.Y.start();(this.j||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.Jf(this.player,!1);gF(this)?(Z9(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.Z.select(!0):this.Z.s0():this.videoData.autonavState===3&&this.Z.xd()):(g.Jf(this.player,!0),Z9(this));Q!==this.LH&&this.player.logVisibility(this.element,!0)};
g.S.hide=function(){var Q=this.LH;yl.prototype.hide.call(this);this.Z.xd();Z9(this);Q!==this.LH&&this.player.logVisibility(this.element,!1)};
g.S.c$3=function(Q){Q.target===this.element&&this.nZ()};
g.S.nZ=function(){var Q,z,H,f;var b=((Q=this.videoData)==null?0:(z=Q.suggestions)==null?0:z.length)?(H=this.videoData)==null?void 0:H.suggestions:[(f=this.videoData)==null?void 0:g.lF(f)];if(b.length){g.SK(this.element,"ytp-endscreen-paginate");var L=this.K.A8(!0,this.K.isFullscreen());if(Q=g.EZ(this.K))Q=Q.iW()?48:32,L.width-=Q*2;var u=L.width/L.height;f=96/54;z=Q=2;var X=Math.max(L.width/96,2),v=Math.max(L.height/54,2);H=b.length;var y=H*4;for(y-=4;y>0&&(Q<X||z<v);){var q=Q/2,M=z/2,C=Q<=X-2&&y>=
M*4,t=z<=v-2&&y>=q*4;if((q+1)/M*f/u>u/(q/(M+1)*f)&&t)y-=q*4,z+=2;else if(C)y-=M*4,Q+=2;else if(t)y-=q*4,z+=2;else break}f=!1;y>=12&&H*4-y<=6&&(z>=4||Q>=4)&&(f=!0);y=Q*96;X=z*54;u=y/X<u?L.height/X:L.width/y;u=Math.min(u,2);y=Math.floor(Math.min(L.width,y*u));X=Math.floor(Math.min(L.height,X*u));L=this.table.element;L.ariaLive="polite";g.j$(L,y,X);g.q2(L,{marginLeft:y/-2+"px",marginTop:X/-2+"px"});this.Z.yV(g.lF(this.videoData));this.Z instanceof XW&&vF(this.Z);g.qP(this.element,"ytp-endscreen-takeover",
gF(this));Z9(this);y+=4;X+=4;u=0;L.ariaBusy="true";for(v=0;v<Q;v++)for(q=0;q<z;q++)if(M=u,t=0,f&&v>=Q-2&&q>=z-2?t=1:q%2===0&&v%2===0&&(q<2&&v<2?q===0&&v===0&&(t=2):t=2),M=g.y4(M+this.L,H),t!==0){C=this.stills[u];C||(C=new pz(this.player),this.stills[u]=C,L.appendChild(C.element));var E=Math.floor(X*q/z),G=Math.floor(y*v/Q),x=Math.floor(X*(q+t)/z)-E-4,J=Math.floor(y*(v+t)/Q)-G-4;g.gW(C.element,G,E);g.j$(C.element,J,x);g.q2(C.element,"transitionDelay",(q+v)/20+"s");g.qP(C.element,"ytp-videowall-still-mini",
t===1);g.qP(C.element,"ytp-videowall-still-large",t>2);t=Math.max(J,x);g.qP(C.element,"ytp-videowall-still-round-large",t>=256);g.qP(C.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.qP(C.element,"ytp-videowall-still-round-small",t<=96);M=b[M];C.suggestion!==M&&(C.suggestion=M,t=C.api.C(),E=g.un(C.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",uX(C,M,E),g.xh(t)&&!C.api.V("web_player_log_click_before_generating_ve_conversion_params")&&(t=M.ma(),E={},g.yw(C.api,"addEmbedsConversionTrackingParams",
[E]),t=g.Ve(t,E),C.updateValue("url",t)),(M=(M=M.sessionData)&&M.itct)&&C.api.setTrackingParams(C.element,M));u++}L.ariaBusy="false";g.qP(this.element,"ytp-endscreen-paginate",u<H);for(b=this.stills.length-1;b>=u;b--)Q=this.stills[b],g.Sz(Q.element),g.S5(Q);this.stills.length=u}};
g.S.onVideoDataChange=function(){var Q=this.player.getVideoData(1);this.videoData!==Q&&(Q!=null&&g.lF(Q)?(this.L=0,this.videoData=Q,this.nZ()):this.player.On("missg",{vid:(Q==null?void 0:Q.videoId)||"",cpn:(Q==null?void 0:Q.clientPlaybackNonce)||""}))};
g.S.Lm=function(){this.L+=this.stills.length;this.nZ()};
g.S.kH=function(){this.L-=this.stills.length;this.nZ()};
g.S.qq=function(){return this.Z.JB()};
g.S.JC=function(Q){Q===1?(this.j=!1,this.D=this.videoData.clientPlaybackNonce,this.Z.zY(),this.LH&&this.nZ()):(this.j=!0,this.LH&&gF(this)&&(Q===2?this.Z.s0():Q===3&&this.Z.xd()))};
g.S.qw=function(Q){if(Q){for(Q=0;Q<this.stills.length;Q++)this.K.logVisibility(this.stills[Q].element,!0);this.JC(1)}else this.D=null,this.j=!1;this.nZ()};
g.S.T1=function(){return this.LH&&gF(this)};g.p(Gk,yl);Gk.prototype.hasSuggestions=function(){var Q;return(Q=this.Z)==null?void 0:Q.hasSuggestions()};
Gk.prototype.show=function(){if(this.player.getPlayerState()!==3){yl.prototype.show.call(this);var Q=this.B;if(Q){var z=this.Z.hasSuggestions();g.qP(this.element,"ytp-shorts-branded-ui",z);z?Q.show():Q.hide()}var H;(H=g.EZ(this.player))==null||H.kK(!0);this.player.logVisibility(this.element,!0);this.watchButton.pH(!0)}};
Gk.prototype.hide=function(){yl.prototype.hide.call(this);var Q;(Q=g.EZ(this.player))==null||Q.kK(!1);this.player.logVisibility(this.element,!1);this.watchButton.pH(!1)};g.p(kMm,g.g3);g.S=kMm.prototype;g.S.k7=function(){var Q=this.player.getVideoData(),z=Q.mutedAutoplay&&(Q.limitedPlaybackDurationInSeconds>0||Q.endSeconds>0||Q.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.B)&&!z)return!0;var H;var f=!!((Q==null?0:g.lF(Q))||(Q==null?0:(H=Q.suggestions)==null?0:H.length));f=!dHs(this.player)||f;Q=Q.Tw;H=this.player.jq();return f&&!Q&&!H&&!z};
g.S.T1=function(){return this.endScreen.T1()};
g.S.ZHv=function(){return this.T1()?this.endScreen.qq():!1};
g.S.zv=function(){this.player.Ys("endscreen");g.g3.prototype.zv.call(this)};
g.S.load=function(){var Q=this.player.getVideoData();var z=Q.transitionEndpointAtEndOfStream;if(z&&z.videoId){var H=this.player.xt().Hq.get("heartbeat"),f=g.lF(Q);!f||z.videoId!==f.videoId||Q.Cs?(this.player.cN(z.videoId,void 0,void 0,!0,!0,z),H&&H.Mk("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),Q=!0):Q=!1}else Q=!1;Q||(g.g3.prototype.load.call(this),this.endScreen.show())};
g.S.unload=function(){g.g3.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.S.onCueRangeEnter=function(Q){this.k7()&&(this.endScreen.created||this.endScreen.create(),Q.getId()==="load"&&this.load())};
g.S.onCueRangeExit=function(Q){Q.getId()==="load"&&this.loaded&&this.unload()};
g.S.onVideoDataChange=function(){w4J(this);this.D&&mHL(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.Z?this.endScreen=new Mw(this.player):this.endScreen=new nz(this.player),g.W(this,this.endScreen),g.sZ(this.player,this.endScreen.element,4))};g.nA("endscreen",kMm);})(_yt_player);
